6:39:05.447 PM
   	at frc.robot.Main.main(Main.java:18)  	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:463)  	at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:373)  	at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:131)  	at edu.wpi.first.wpilibj.IterativeRobotBase.loopFunc(IterativeRobotBase.java:328)  	at frc.robot.Robot.robotPeriodic(Robot.java:59)  	at edu.wpi.first.wpilibj2.command.CommandScheduler.run(CommandScheduler.java:280)  	at edu.wpi.first.wpilibj2.command.SequentialCommandGroup.execute(SequentialCommandGroup.java:67)  	at edu.wpi.first.wpilibj2.command.ParallelDeadlineGroup.execute(ParallelDeadlineGroup.java:93)  	at edu.wpi.first.wpilibj2.command.SequentialCommandGroup.execute(SequentialCommandGroup.java:67)  	at edu.wpi.first.wpilibj2.command.SequentialCommandGroup.execute(SequentialCommandGroup.java:67)  	at com.pathplanner.lib.commands.PPSwerveControllerCommand.execute(PPSwerveControllerCommand.java:139)  	at com.pathplanner.lib.server.PathPlannerServer.sendPathFollowingData(PathPlannerServer.java:122)  	at com.pathplanner.lib.server.PathPlannerServer.sendToClients(PathPlannerServer.java:46)  	at java.base/java.util.ArrayList$Itr.next(Unknown Source)  	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)  Error at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source): Unhandled exception: java.util.ConcurrentModificationException ERROR  1  Unhandled exception: java.util.ConcurrentModificationException  java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source) 
